10.1 Допы
RuslanMurin/SkillBoxStudy pull request #12
Opened 2020-06-24 15:38 UTC by RuslanMurin

Доброго времни суток.
Все сделал кроме встравивания коллекции в таблицу(Облазил уже все, но тема видимо совсем редкая)
Одна проблема: Что-то идёт не так с встраиванием collectionView в tableView:
1. Правильно ли понимаю суть?(Делаю коллекцию в классе ячейки таблицы. Птыался сделать все в классе VC, прилодение не реагировало вообще)
2.Что для таблицы Delegate и DataSource будет ViewController - это понятно. А для CollectionView? При варианте и таблицы, и Вью контроллера вылетает.
3.чейки таблицы формируются, контент в них не заполняется, на каком уровне делать это заполнение?(В loadFromNib()??)
4. И последний вопрос: часто видел, что встраивать коллекции в таблицы идея не очень хорошая. Это так? Или дело касается только таблиц и коллекций с неопределенным количеством ячеек?

2020-07-01 15:01 UTC, ios-review commented on 10.1. Additional/10.1. Additional/TablesAndCollections/AlbumTableViewCell.swift
> +class ImagesContainer{
В каждом альбоме получается все фотографии и при том одни и те же.

2020-07-01 15:03 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    var albumNames: String
Используем константное свойство, если не планируем его изменять.

Картинки, связанные с альбомом можно добавить в эту структуру.

```
struct Albums {
    let name: String
    let images: [UIImage]
}
```

Именование albumNames в структуре Album является дублированием.
Как думаете, почему?

2020-07-01 15:03 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/RandomImagesViewController.swift
> +class RandomImagesViewController: UIViewController {
👍

2020-07-01 15:03 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/SecondScrollViewController.swift
> +class SecondScrollViewController: UIViewController {
🔥

2020-08-04 17:40 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/TablesAndCollections/AlbumTableViewCell.swift
> +        }
Спасибо за подсказку, сокаратил

2020-08-04 18:24 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/TablesAndCollections/AlbumTableViewCell.swift
> +struct Images{
Я её в принципе убрал, так как по сути не нужна, потому что в ней хранится один тип данных. Полезна она может быть как раз в случае, если нужно хранить в одной структуре и картинки, и альбомы.

2020-08-04 18:24 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/TablesAndCollections/AlbumTableViewCell.swift
> +class ImagesContainer{
Исправил

2020-08-04 18:25 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/RandomImagesViewController.swift
> +class RandomImagesViewController: UIViewController {
🙌🏻

2020-08-04 18:25 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/SecondScrollViewController.swift
> +class SecondScrollViewController: UIViewController {
☺️

2020-08-04 18:27 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    var albumNames: String
Я вообще убрал структуру, отсюда вопрос: имеет ли место быть хранить названия альбомов и картинки отдельно?

2020-08-04 18:28 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    var albumNames: String
Дублирование по сути происходит потому что приходиться переопределять albumNames еще и в классе, что создает лишние строчки

2020-08-04 18:32 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/TablesAndCollections/AlbumTableViewCell.swift
> +struct Images{
По поводу передачи данных: 
-я очень долго пытался передать данные с помощью делегата(вообще ничего не полилось, и потратил впустую кучу времени). Применим ли такой метод в данном случае?
-когда я вызываю .reloadData приложение вылетает, а без него всё работает. Почему?

2020-08-05 14:29 UTC, ezaji commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    static func albumsNames() -> [String]{
```
static var albumNames: [String] {
    return ...
}
```

2020-08-05 14:33 UTC, ezaji commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    static func albumsNames() -> [String]{
Другой возможный вариант, который более безопасен, чем использование индексов, это создание модели и передача модели в ячейки.
Например,
```
struct Album {
    let name: String
    let images: [UIImage]
}
```
В контейнере создаем полностью все альбомы.
Отображаем имена альбомов.
А в ячейки передаем картинки, связанные с альбомом.

Разделение этой информации на два разных класса и использование индекса в качестве связи может привести к большому количеству багов.

Доделаем этот пункт?

2020-08-05 14:33 UTC, ezaji commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    let albumView = AlbumTableViewCell()
Это зачем?

2020-08-05 14:34 UTC, ezaji commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +        cell.sendedIndex = indexPath.section
здесь передавать массив images из структуры Album.

2020-08-05 15:23 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    static func albumsNames() -> [String]{
В итоге я создал один класс, а не структуру, так ведь логичнее?

2020-08-05 15:24 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    let albumView = AlbumTableViewCell()
Осталось от старой попытки передать данные через делегат

2020-08-05 15:24 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +    let albumView = AlbumTableViewCell()
Убрал

2020-08-05 15:25 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +        cell.sendedIndex = indexPath.section
Сделал

2020-08-25 04:59 UTC, ios-review requested changes
Класс один для данных - здорово!

Сделаем так, чтобы данные было безопасно создавать/изменять/удалять?

2020-08-25 04:59 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
>      }
Данный код небезопасный.
Можно изменить один массив и забыть изменить другой, что приведет к падению приложения, что ухудшит пользовательский опыт, если код попадет на продакшн.

Использование типизированных структур, описывающих модель данных, наиболее читаемый и безопасный способ.
Модель:
```
struct Album {
    let name: String
    let images: [UIImage]
}
```
Любой разработчик, видя данный код, будет понимать, что в приложении существует альбом, а также какие данные этот альбом содержит.
Теперь с помощью структуры можно создать любое количество альбомов:
```
let albums = [
    Album(name: "cities", images: (1...6).compactMap { UIImage(named: "c\($0)") }),
    Album(name: "cats", images: (1...8).compactMap { UIImage(named: "cat\($0)") })
]
```
Для добавления нового альбома видно, что необходимо задать имя альбома и картинки для него.
Также при удалении альбома достаточно удалить создание этой структуры.

В случае двух массивов можно ошибиться критически.

2020-09-01 11:53 UTC, ios-review requested changes
Правим еще раз.

2020-09-01 11:53 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +                  Album(name: AlbumsContainer.names[3], images: AlbumsContainer.images[3])]
Такой код все еще остаётся небезопасным.
Решили добавить новый альбом с картинками.
Обновили names, но забыли добавить к images.
Добавили в albums новый альбом так:
`Album(name: AlbumsContainer.names[4], images: AlbumsContainer.images[4])`

Решили не проверять код, так как супер простое изменение.
Или забыли проверить.
Не важно.
Выложили в App Store.
Пользователь скачал приложение.
Зашел на экран.
И приложение упало.
Пользователь оказался лояльным и попробовал еще 5 раз.
А на 6-й послал наше приложение)
И так будет с 90% пользователей. И они никогда не вернутся больше.

Безопасно создавать альбом с использование сырых данных:
```
let albums = [Album(name: "1", images: (1...6).map { UIImage(named: "c\($0)") }),
                       Album(name: "2", images: (1...6).map { UIImage(named: "c\($0)") }),
                       Album(name: "3", images: (1...6).map { UIImage(named: "c\($0)") }),
                       Album(name: "4", images: (1...6).map { UIImage(named: "c\($0)") })]
```
В таком случае при добавлении нового альбома ничего не поломается.
Или при удалении текущего альбома.

В случае контейнера с двумя разными массивами, которые вместе формируют общее состояние, можно придти к тому, что один массив будет изменен, а второй нет, что приведет к крашу приложения.

2020-09-01 11:56 UTC, ios-review commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +                  Album(name: AlbumsContainer.names[3], images: AlbumsContainer.images[3])]
Проверьте мое предположение.
1. Добавьте в names новое имя альбома.
2. Оставьте без изменения массив images.
3. Добавьте новый альбом в массив albums:
`Album(name: AlbumsContainer.names[4], images: AlbumsContainer.images[4])`
4. Запустите приложение.

Какой результат?

2020-09-01 12:10 UTC, RuslanMurin commented on 10.1. Additional/10.1. Additional/ViewControllers/GalleryViewController.swift
> +                  Album(name: AlbumsContainer.names[3], images: AlbumsContainer.images[3])]
Да, действительно, при значении nil вылетает

2020-09-27 09:26 UTC, ios-review approved these changes
👌

merge

2020-09-27 10:53 UTC, merged