11. Собственные UI
RuslanMurin/SkillBoxStudy pull request #13
Opened 2020-06-24 15:38 UTC by RuslanMurin

Доброго времени суток, готова основная домашка.
Возникла одна сложность: когда делал Часы, не мог сделать 12 меток. Видимо плохо совсем с геометрией=) Правильно ведь думаю, что надо делать цикл for-in и вычислять координаты через угол?

2020-06-30 12:07 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +//@IBDesignable
Зачем закомментировали?

Без этого не рисуется в сториборде.

2020-06-30 12:10 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +        super.layoutSubviews()
https://developer.apple.com/documentation/uikit/uiview/1622482-layoutsubviews может вызываться несколько раз.

В общем случае рекомендуется переопределять инициализаторы https://developer.apple.com/documentation/uikit/uiview/1622488-init и создавать иерархию там.
В layoutSubviews() устанавливаются только frame для subviews.

Также попробуйте воспользоваться https://developer.apple.com/documentation/objectivec/nsobject/1402908-prepareforinterfacebuilder

2020-06-30 12:12 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +            marker1.transform = CGAffineTransform(rotationAngle: angle)
Эту идею можно развить, чтобы поворачивать hour line или minute line в зависимости от конкретного значения времени.

2020-07-04 12:31 UTC, RuslanMurin commented on CustomUI/CustomUI/ClockView.swift
> +//@IBDesignable
Сильно грузился мак

2020-08-04 18:37 UTC, RuslanMurin commented on CustomUI/CustomUI/ClockView.swift
> +        super.layoutSubviews()
Вроде все получилось. Не получался один момент: в Attributes Inpector Стандартные значения для UI обозначаются как --. Можно ли сделать так, чтобы они были сразу от значения из prepareForInterfaceBuilder()?

2020-08-04 18:37 UTC, RuslanMurin commented on CustomUI/CustomUI/ClockView.swift
> +            marker1.transform = CGAffineTransform(rotationAngle: angle)
Сделал

2020-08-05 14:40 UTC, ezaji commented on CustomUI/CustomUI/ClockView.swift
> +        customizeView()
Вьюхи все еще добавляются в иерархию в layoutSubviews()
Воспользуйтесь для этого https://developer.apple.com/documentation/uikit/uiview/1622488-init

В layoutSubviews можно только изменять frame у дочерних вью (еще bounds, centerPoint и transform, так как они влияют на frame).
Все остальное должно быть в инициализаторе и prepareForInterfaceBuilder

2020-08-05 14:40 UTC, ezaji commented on CustomUI/CustomUI/CustomSegmentControl.swift
> +        substrateView.frame = CGRect(x: 5, y: 5, width: (layer.frame.width - 15) / 2, height: layer.frame.height - 10)
В этом методе только этот код допустим.

2020-08-05 14:40 UTC, ezaji commented on CustomUI/CustomUI/CustomSegmentControl.swift
> +        else{ return }
пустой else?

2020-08-05 14:40 UTC, ezaji commented on CustomUI/CustomUI/FIrstCustomView.swift
> +
Зачем это?

2020-08-05 14:41 UTC, ezaji commented on CustomUI/CustomUI/FIrstCustomView.swift
> +        setupButton(multiplier: roundingMultiplier, color: buttonColor, indent: indentSize)
frame и layoutSubviews.

2020-08-05 14:41 UTC, ezaji commented on CustomUI/CustomUI/ClockView.swift
> +        isSetuped = true
Думаю в этом нет необходимости.

2020-08-05 14:42 UTC, ezaji commented on CustomUI/CustomUI/ClockView.swift
> +        super.layoutSubviews()
Не думаю, что можно так сделать.
"--" - означает значение по умолчанию.

2020-08-05 15:39 UTC, RuslanMurin commented on CustomUI/CustomUI/ClockView.swift
> +        isSetuped = true
Убрал

2020-08-05 15:39 UTC, RuslanMurin commented on CustomUI/CustomUI/FIrstCustomView.swift
> +
Убрал

2020-08-05 15:41 UTC, RuslanMurin commented on CustomUI/CustomUI/CustomSegmentControl.swift
> +        else{ return }
Нет необходимости в else - убрал

2020-08-25 05:31 UTC, ios-review requested changes
1. Менять значения по месту с использованием didSet.
2. Необходимо убедиться, что все вызывается в нужный момент.
Сейчас это не так.
3. Проверьте алгоритм.

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
>              addSubview(line)
Вьюхи все еще добавляются в иерархию в layoutSubviews.

layoutSubviews служит только для layout subviews.
В этом методе необходимо вручную вычислять frame подвьюх или другие свойства, которые связаны с frame.
Например, можно вычислять bounds, centerPoint, transform, даже anchorPoint.

Хотя как правило только frame. Все остальное вычисляется по месту происхождения события.

Добавлять подвьюхи в иерархию необходимо в момент создания самой вью, так как создается вью всего один раз за все время ее жизни.
Моментом создания является инициализатор.

Пожалуйста, реализуйте инициализатор и перенесите туда весь код, который связан с первоначальной настройкой вью по умолчанию, включая добавление подвьюх, которые требуется добавить всего один раз.

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +        updateSeconds()
В инициализаторе нужно только создать все подвьюхи и добавить их в ClockView.
В инициализаторе нельзя определить их frame, так как размер самой ClockView еще не известен полностью.

Разместить подвьюхи можно тогда и только тогда, когда размер ClockView будет известен.
layoutSubviews служит таким методом, где известен размер ClockView и на его базе (как системы координат) можно вычислить координаты и размер остальных подвьюх.

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +        layer.cornerRadius = layer.frame.width / 2
setClock вызывается в инициализаторе.
frame еще не известен точно в инициализаторе.

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +        layer.cornerRadius = layer.frame.width / 2
Рекомендую к изучению документацию:
https://developer.apple.com/documentation/uikit/uiview/1622482-layoutsubviews

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/ClockView.swift
> +        layer.cornerRadius = layer.frame.width / 2
https://www.vadimbulavin.com/view-auto-layout-life-cycle/

2020-08-25 05:31 UTC, ios-review commented on CustomUI/CustomUI/FIrstCustomView.swift
>      }
Пустой метод?

2020-08-25 20:55 UTC, RuslanMurin commented on CustomUI/CustomUI/FIrstCustomView.swift
>      }
Расставил на места

2020-08-25 20:55 UTC, RuslanMurin commented on CustomUI/CustomUI/ClockView.swift
> +        layer.cornerRadius = layer.frame.width / 2
Спасибо, изучил

2020-09-01 11:46 UTC, ios-review approved these changes
Гуд!

Все вызовы в нужных методах!

Мерж.

2020-09-01 12:00 UTC, merged