Готово
RuslanMurin/SkillBoxStudy pull request #14
Opened 2020-09-26 15:55 UTC by RuslanMurin

Доброго времени суток, Дмитрий

Хотелось бы поинтересоваться, как я могу сделать фиксированный frame для моих UIView. Программно получается, а возможно ли это сделать для Storyboard? Как это, например, обстоит с UISwitch.

2020-09-27 10:04 UTC, ios-review requested changes
По коду все супер!

Есть пара багов, которые нужно поправить.

2020-09-27 10:04 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +class CustomSwitcherView: UIView {
Полностью запретить устанавливать размер для своей вью в сториборде нельзя.
UISwitch запрещает устанавливать размер, хотя его все равно можно изменить с помощью констрейнтов.
Правда и в этом случае видимый контент будет отображаться только на маленькой части.

Можно задать естественный размер для вью с помощью https://developer.apple.com/documentation/uikit/uiview/1622600-intrinsiccontentsize
```
final class View: UIView {
    override var intrinsicContentSize: CGSize {
        return CGSize(width: 100, height: 100)
    }
}
```

В таком случае после установки отступов слева и сверху (например) для вью, эти размеры будут автоматически установлены и вью будет отображено 100х100.

Более подробно по ссылке https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AutolayoutPG/ViewswithIntrinsicContentSize.html

2020-09-27 10:04 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +                    self.switcherButton.center.x += self.frame.width - self.switcherButton.frame.width - 10
Может попробовать с использованием констрейнтов?

Создать слева и справа, при этом справа деактивировать.
А затем при изменении состояния активировать/деактивировать нужные.

2020-09-27 11:03 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/BatteryIndicator.swift
> +    override func draw(_ rect: CGRect) {
Сделал повторную обводу после отрисовки заряда

2020-09-27 11:15 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/PasswordTextField.swift
> +class PasswordTextField: UIView {
Добавил констрейнт на размер frame.height

2020-09-27 17:09 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +                    self.switcherButton.center.x += self.frame.width - self.switcherButton.frame.width - 10
Сделал. Я так понимаю, способ более безопасный?

2020-09-27 17:50 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +        super.init(frame: CGRect(x: .zero, y: .zero, width: 100, height: 40))
теперь в нем cornerRadius

2020-09-27 17:51 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +        layer.cornerRadius = 20
убрал в init, НО: switcherButton.layer.cornerRadius  все равно определяется только в layoutSubviews()

2020-09-28 16:20 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +class CustomSwitcherView: UIView {
Добавил

2020-09-29 09:29 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +                    self.switcherButton.center.x += self.frame.width - self.switcherButton.frame.width - 10
Оба способа - ок.

Просто как вторая возможная реализация.

2020-09-29 09:44 UTC, ios-review requested changes
Нашел, что еще можно поправить 😏😏😏

2020-09-29 09:44 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/BatteryIndicator.swift
> +        batteryBezier.stroke()
Такой же код есть и выше.

Что если сперва рисовать заливку, а затем обводку?

2020-09-29 09:44 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
>      }
В инициализаторах не будет switcherButton никогда, так как вся вью реализована в xib.
@IBOutlet не проставляются в инициализаторах.

Инициализаторы в данном случае совсем не нужны, так как вью нельзя создать с помощью init(frame:).
Создать можно, но это будет не работающая вью.

@IBOutlet доступны в awakeFromNib для объектов, загруженных из xib.
```
    override func awakeFromNib() {
        super.awakeFromNib()
        
        switcherButton.layer.cornerRadius = 15
    }
```

2020-09-29 09:44 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
>      }
awakeFromNib вызывается один раз, что эффективнее реализации в layoutSubviews.

2020-09-29 09:44 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +            self.trailingConstraint.isActive.toggle()
Сейчас данные изменения не анимируются.
Для анимации констрейнтов необходимо их изменять за пределами анимации, а внутри блока анимации вызвать view.layoutIfNeeded().
```
self.leadingConstraint.isActive.toggle()
self.trailingConstraint.isActive.toggle()
UIView.animate(withDuration: 0.5) {
    self.layoutIfNeeded()
}
```

2020-09-29 09:44 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/PasswordTextField.swift
> +                pathLenght = self.layer.frame.width / 4
Странно, что полоска показывается при нуле символах.
Кажется, что полоса прогресса не должна показываться или быть пустой при нуле символах.

Что думаете?

2020-10-27 19:44 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/PasswordTextField.swift
> +                pathLenght = self.layer.frame.width / 4
Вообще убрал полоску при 0 символов

2020-10-27 19:46 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
> +            self.trailingConstraint.isActive.toggle()
Как раз при пытался использовать .toggle внутри анимации - не получалось. Буду знать

2020-10-27 20:24 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/BatteryIndicator.swift
> +        batteryBezier.stroke()
Но если рисовать сперва заливку, а затем обводу, то сначала нарисует заливка в виде прямоугольника зеленого цвета, то есть при отрисовке заряда например 100% этот прямоугольник выйдет за пределы обводки. Я пытался найти метод, который обрезает контент вне UIBezierPath который был нарисован до его построения, но не нашел. Есть только .addCurve(), но он обрезает контент, только при рисовании после построения. А задваивается обводка в коде дабы индикатор заряда не залезал на половину толщины обводки

2020-10-27 20:29 UTC, RuslanMurin commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/CustomSwitcherView.swift
>      }
Убрал инициализаторы и layoutSubviews(), собственный cornerRadius для View задал так же в awakeFromNib()

2020-10-28 12:33 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/BatteryIndicator.swift
> +        batteryBezier.stroke()
Если так:
```
    override func draw(_ rect: CGRect) {
        let percent = self.frame.width / 100 * CGFloat(charge)
        var pathColor: UIColor = .red
        
        switch self.charge {
        case ...25:
            pathColor = .red
        case 26...80:
            pathColor = .orange
        case 80...:
            pathColor = .systemGreen
        default:
            break
        }
        let batteryBezier = UIBezierPath()
        batteryBezier.move(to: CGPoint(x: 2, y: 2))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 10, y: 2))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 10, y: self.frame.height / 2 - 10))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 2, y: self.frame.height / 2 - 10))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 2, y: self.frame.height / 2 + 10))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 10, y: self.frame.height / 2 + 10))
        batteryBezier.addLine(to: CGPoint(x: self.frame.width - 10, y: self.frame.height - 2))
        batteryBezier.addLine(to: CGPoint(x: 2, y: self.frame.height - 2))
        batteryBezier.close()
        UIColor.black.setStroke()
        batteryBezier.lineWidth = 4
        batteryBezier.addClip()
        
        
        
        let pathRect = CGRect(x: 4, y: 4, width: percent, height: self.frame.height - 8)
        let path = UIBezierPath(rect: pathRect)
        let color: UIColor = pathColor
        color.setFill()
        path.fill()
        
        batteryBezier.stroke()
    }
```

2020-10-28 12:34 UTC, ios-review commented on 11.1CustomUI-Additional/11.1CustomUI-Additional/CustomViews/BatteryIndicator.swift
> +        batteryBezier.stroke()
Сперва делается clip, чтобы рисование производилось только внутри обводки.
После рисуем заливку.
И затем обводку с помощью store.

2020-10-28 12:35 UTC, ios-review approved these changes
🔥

мержим реквест

2020-10-28 16:56 UTC, merged