Готово.
RuslanMurin/SkillBoxStudy pull request #15
Opened 2020-09-26 15:55 UTC by RuslanMurin

Доброго времени суток, Дмитрий

Правильно ли я сделал, что преобразовал не весь JSON, а только те его части, которые мне нужны?

2020-09-27 10:09 UTC, ios-review requested changes
В ПР вошло слишком много изменений, непосредственно несвязанных с решением.
Папку Pods необходимо добавить в .gitignore.
Предлагаю поискать универсальный .gitignore для iOS проектов и добавить его в репо.

Папка Pods не нужна в репозитории, так как код из этой папку всегда можно установить локально с помощью команды pod install.
Весь код из папки Pods расположен в отдельных репозитория разработчиков данных библиотек.

<img width="1676" alt="Screenshot 2020-09-27 at 17 05 45" src="https://user-images.githubusercontent.com/62285448/94362225-0e74a100-00e4-11eb-9f7e-62de5d3d7dfa.png">

2020-09-29 10:01 UTC, ios-review requested changes
В ПР не должно быть только тех файлов, которые можно установить самостоятельно локально с помощью pod install.
Такие файлы всегда расположены только в папке Pods/.
Все остальные файлы должны присутствовать, включая Podfile и Podfile.lock, так как команда pod install берет информацию из этих файлов и скачивает с гитхаба или других хостингов нужные библиотеки.

Верните Podfile)

Предлагаю немного доработать код и разделение на классы.
Можно заметить, что сигнатуры функций у сервисов погоды одинаковые. Отличаются только реализации.
В связи с этим следующий подход будет более коротким и соответствовать принципам SOLID.
1. Создать протокол WeatherService с двумя функциями.
2. Реализовать два класса, принимающих данный протокол.
URLSessionWeatherService и AlamofireWeatherService.
В каждом использовать соответствующую библиотеку для сети.
3. Создать 1 класс WeatherViewController.
Добавить в него свойство weatherService с типом протокола WeatherService.
4. Создать UITabBarController и 2 объекта WeatherViewController в коде.
В каждый из этих контроллеров присвоить разные реализации протокола WeatherService.
5. Для создания UI в коде можно воспользоваться ссылкой https://stackoverflow.com/questions/57963647/how-to-create-ui-programmatically-in-xcode-11
Общий алгоритм следующий:
- создать UITabBarController
- создать WeatherViewController и сконфигурировать его URLSessionWeatherService
- создать второй WeatherViewController и сконфигурировать его AlamofireWeatherService
- передать в UITabBarController оба контроллера
- назначить для UIWindow в качестве rootViewController UITabBarController
Реализацию WeatherViewController можно оставить в сториборде.
Для создания вью контроллера из сториборда в коде
- создать сторибоард https://developer.apple.com/documentation/uikit/uistoryboard/1616216-init
первый параметр - имя сториборда, второй - nil
- создать view controller https://developer.apple.com/documentation/uikit/uistoryboard/1616214-instantiateviewcontroller
где индентификатор - это Storyboard ID в сториборде
6. Для декодирования данных из Dictionary в объект структуры в настоящее время используется Codable.
Попробуете использовать его вместо ручного маппинга данных?
https://developer.apple.com/documentation/foundation/archives_and_serialization/encoding_and_decoding_custom_types

2020-10-27 21:25 UTC, RuslanMurin commented on 12.0JSON/12.0JSON/Tables and Collections/WeekTableViewCell.swift
> +    }
Убрал

2020-10-27 21:31 UTC, RuslanMurin commented on 12.0JSON/12.0JSON/Tables and Collections/AlamoWeekTableViewCell.swift
> +class AlamoWeekTableViewCell: UITableViewCell {
Вообще убрал этот класс

2020-11-01 04:51 UTC, ios-review approved these changes
.gitignore - 👌
Реквест - 👌
Модуль - 👌

Мержим.

2020-11-01 04:51 UTC, ios-review commented on 12.0JSON/12.0JSON/JSON/WeeklyWeather.swift
> +struct Weather1: Codable {
В чем разница Weather и Weather1?

2020-11-01 04:51 UTC, ios-review commented on 12.0JSON/12.0JSON/SceneDelegate.swift
> +        window?.rootViewController = UINavigationController(rootViewController: MainTabBarController())
UINavigationController не нужен.
 Можно сразу создать MainTabBarController и его сделать rootViewController.

2020-11-01 04:51 UTC, ios-review commented on 12.0JSON/12.0JSON/ViewControllers/MainTabBarController.swift
> +        self.viewControllers = controllers
Не понял, почему это здесь, а не во viewDidLoad.
viewWillAppear может быть вызвано несколько раз. Перед самым появлением вьюхи контроллера на экране.
Заблокировать/разблокировать/заблокировать/разблокировать. Так этот код будет вызван 2 раза.
Зачем данный код вызывать несколько раз?

Кажется, что это должно быть в viewDidLoad.

2020-11-01 04:51 UTC, ios-review commented on 12.0JSON/12.0JSON/ViewControllers/MainTabBarController.swift
> +        self.viewControllers = controllers
Проще, нагляднее.
```
class MainTabBarController: UITabBarController {
    
    let urlViewController: WeatherViewController = {
        let vc = WeatherViewController.storyboardInstance()
        vc.title = "URL"
        vc.weatherService = URLSessionWeatherService()
        return vc
    }()
    let alamofireViewController: WeatherViewController = {
        let vc = WeatherViewController.storyboardInstance()
        vc.title = "Alamofire"
        vc.weatherService = AlamofireWeatherService()
        return vc
    }()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.viewControllers = [urlViewController, alamofireViewController]
    }
}
```

2020-11-01 04:51 UTC, ios-review commented on 12.0JSON/12.0JSON/ViewControllers/WeatherViewController.swift
> +        })
Сейчас два запроса выполняются последовательно.
Для увеличение отзывчивости можно запросы выполнить параллельно.
```
        weatherService?.dayLoad(completion: { weather in self.weather = weather
             self.cityLabel.text = weather.name
             self.tempLabel.text = "\(Int(weather.main.temp - 273.0)) C"
             self.descriptionLabel.text = weather.weather[0].weatherDescription
              self.mainDescriptionLabel.text = "Сейчас \(weather.weather[0].weatherDescription). Максимальная температура воздуха: \(Int(weather.main.tempMax - 273.0)) C. Минимальная температура воздуха: \(Int(weather.main.tempMin - 273.0)) C. Атмосферное давление: \(weather.main.pressure)мм.рт.ст. Влажность: \(weather.main.humidity)%."
          })
          self.weatherService?.weekLoad(completion: { week in self.week = week
              self.mainTableView.reloadData()
          })
```

2020-11-21 18:03 UTC, merged