13.0 Анимации
RuslanMurin/SkillBoxStudy pull request #16
Opened 2020-10-27 21:43 UTC by RuslanMurin

2020-10-28 12:49 UTC, ios-review requested changes
Реализация - топ👍

Модуль можно было бы принять.
Предлагаю еще немного поизучать анимации.
Подробнее на скилбоксе.

+ Некоторые упрощения по коду.

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +        numberLabel.text = action.actionsArray[action.currentIndex]
оч сложно

Что если из индекса делать строку?
`label.text = "\(currentIndex + 1)"`

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +        print(action.currentIndex)
зачем print?

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +            squareView.layer.removeAllAnimations()
в каждом case есть
можно вынести за пределы switch

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +            }, completion: { (isCompleted) in self.squareView.backgroundColor = .systemRed })
isCompleted не используется
можно так:
`{ _ in /* остальной код */ }`

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +                self.squareCenterHorisontalyConstraint.constant = self.view.frame.size.width / 2 - 50
обычно констрейнты меняют за пределами блоков анимаций, а внутри блока анимации только view.layoutIfNeeded()

2020-10-28 12:49 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +}
В таком случае нагляднее было бы создать перечисление, которое моделирует все поддерживаемые в приложении анимации.

```
enum Animation: String {
    case background = "Изменение цвета фона"
    case move = "Перемещение"

    mutating func previous() {
        switch self {
        case .background:
            self = .move
        }
    }

    mutating func next() {
        switch self {
        case .move:
            self = .background
        }
    }
}
```

И в функциях-обработчиках событий нажатия на кнопку:
```
func animatePrevious() {
    currentAnimation.previous()
    animate()
}

func animate() {
    label.text = currentAnimation.rawValue
    switch currentAnimation {
    }
}
```

2020-10-28 17:27 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +        numberLabel.text = action.actionsArray[action.currentIndex]
Согласен - проще

2020-10-28 17:28 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +        print(action.currentIndex)
Делал для себя - забыл убрать

2020-10-28 17:29 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +            squareView.layer.removeAllAnimations()
Изначально делал не для всех кейсов, так как думал, что не для всех типов анимаций оно нужно. Оказалось, что и правда нужно)

2020-10-28 17:30 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +            }, completion: { (isCompleted) in self.squareView.backgroundColor = .systemRed })
Заменил

2020-10-28 17:32 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +                self.squareCenterHorisontalyConstraint.constant = self.view.frame.size.width / 2 - 50
Но в completion все равно оставить нужно?

2020-10-28 17:35 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +                self.squareCenterHorisontalyConstraint.constant = self.view.frame.size.width / 2 - 50
а вот .layoutIfNedded() в completion как я понял совсем не обязателен?

2020-10-28 18:12 UTC, RuslanMurin commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +}
Теперь выглядит интереснее

2020-10-29 12:12 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +                self.squareCenterHorisontalyConstraint.constant = self.view.frame.size.width / 2 - 50
если не анимируете, то не обязательно
рекомендую к прочтению https://tech.gc.com/demystifying-ios-layout/

2020-10-29 12:17 UTC, ios-review approved these changes
👍🔥

мержим

2020-10-29 12:17 UTC, ios-review commented on 13.0-Animations/13.0-Animations/ViewController.swift
> +
Чуть короче и универсальнее.
```
enum Animation: String, CaseIterable {
    case background = "1"
    case move = "2"
    case rounding = "3"
    case rotate = "4"
    case alpha = "5"
    case size = "6"
    case repeating = "7"
    
    mutating func previous() {
        let index = Animation.allCases.firstIndex(of: self) ?? 0
        let previousIndex = index - 1 >= 0 ? index - 1 : 0
        self = Animation.allCases[previousIndex]
    }
}
```

2020-10-29 15:36 UTC, merged