12.1
RuslanMurin/SkillBoxStudy pull request #17
Opened 2020-11-21 18:06 UTC by RuslanMurin

Готово, приятно было работать над знакомой темой))

2020-11-24 13:43 UTC, ios-review requested changes
UI красивый 🔥

Не выполнены условия задания:
- Реализовать пагинацию (дозагрузку персонажей по мере скрола)
- Для загрузки картинки сторонних библиотек использовать нельзя. Попробуйте этот функционал с кэшированием реализовать нативными средствами.

Можно воспользоваться сторонней библиотекой для загрузки картинки.

Также вынести код запроса в отдельный класс.

2020-11-24 13:43 UTC, ios-review commented on 12.1-Rick-And-Morty/12.1-Rick-And-Morty/ViewController.swift
> +            }
Выделить вызов в отдельный сервис.

RickMortyAPI или любое другое название.

2020-11-24 13:43 UTC, ios-review commented on 12.1-Rick-And-Morty/12.1-Rick-And-Morty/ViewController.swift
> +        }
UI не тормозит?

Поищите библиотеки для загрузки картинок.

Данный инициализатор `Data(contentsOf: url)` может сходить в сеть синхронно.
А ходить в сеть дорого по времени, что может "залагать" UI.

2020-12-05 13:12 UTC, RuslanMurin commented on 12.1-Rick-And-Morty/12.1-Rick-And-Morty/ViewController.swift
> +            }
API создал

2020-12-07 04:48 UTC, RuslanMurin commented on 12.1-Rick-And-Morty/12.1-Rick-And-Morty/ViewController.swift
> +        }
Использовал Kingfisher - в сеть уходит асинхронно, можно удобно установить activity indicator, картинки хранит в кэше.

2021-02-02 15:44 UTC, merged