15.0
RuslanMurin/SkillBoxStudy pull request #19
Opened 2020-11-24 11:28 UTC by RuslanMurin

Доброго времени суток, оставил все вопросы в комеентариях в коде.

2020-11-25 09:32 UTC, ios-review requested changes
Задания с функциями в качестве параметров и задания с операторами требуют доработки.

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +let stringNames = names.reduce("") { "\($0) \($1)" }
Добавляется пробел перед первым элементом.
Какие есть способы исправить это?
<img width="1369" alt="Screenshot 2020-11-25 at 16 19 44" src="https://user-images.githubusercontent.com/62285448/100207490-39d80880-2f3a-11eb-83a1-b49d47d7bdc3.png">

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +func testFunc(void: Void) -> Void{
`func testFunc(void: Void) -> Void` равносильно `func testFunc(void: Void)`
Если функция ничего не возвращает, то можно не указывать тип Void.

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +    DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2), execute: { return void })
`execute: { print("Some") }`

Тогда можно проверить результат.

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> + */
👍

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +testFunc(void: print("Hello"))
Функция print будет выполнена сразу и результат ее вычисления будет передан в качестве параметра.

`func testFunc(closure: @escaping () -> Void)`
`testFunc { print("Hi") }`

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +print("Hola") + print("Mundo")
Void - это typealias на пустой кортеж Tuple.
Объявлен так:
`typealias Void = ()`

Ознакомьтесь с синтаксисом замыкающих выражений по ссылке https://docs.swift.org/swift-book/LanguageGuide/Closures.html

`func some(a: () -> Void)`

Тип функции записывается `([parameters]) -> [ReturnValue]`
`func example(a: (Int) -> String, b: (String) -> Int)`

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +}
Функции принимают в качестве параметров обычные типы данных: пустой кортеж Void, массив чисел [Int], кортеж (Int, Int).

Функция как параметр: `([ParameterTypes]) -> [ReturnValue]`

2020-11-25 09:32 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> + Каждый infix оператор принадлежит к своей приоритетной группе.
Приоритет (Precedence) - немного другое понятие.
https://docs.swift.org/swift-book/LanguageGuide/AdvancedOperators.html#ID41

Определения prefix, postfix, infix по ссылке https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html#ID61

2020-12-14 18:35 UTC, RuslanMurin commented on FunctionalProgramming.playground/Contents.swift
> +let stringNames = names.reduce("") { "\($0) \($1)" }
Надеюсь, сделал не слишком сложно

2020-12-14 18:53 UTC, RuslanMurin commented on FunctionalProgramming.playground/Contents.swift
> +    DispatchQueue.main.asyncAfter(deadline: .now() + .seconds(2), execute: { return void })
👍🏻

2020-12-14 18:54 UTC, RuslanMurin commented on FunctionalProgramming.playground/Contents.swift
> +testFunc(void: print("Hello"))
Сделано

2021-01-11 17:49 UTC, RuslanMurin commented on FunctionalProgramming.playground/Contents.swift
> + Каждый infix оператор принадлежит к своей приоритетной группе.
Разделил ответ логичнее, вопрос приоритета сюда не не входит, но это по сути базовая арифметика

2021-01-12 13:06 UTC, ios-review requested changes
С типами функций еще нужно поработать.

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +func completeClosures(a:(), b:()){
Типы параметров a и b являются кортежами без элементов, то есть просто Void.

У типа функции всегда идет список параметров в виде типов в круглых скобках, затем стрелочка, затем возвращаемое значение.

Например,
`func testFunc(_ closure: @escaping () -> Void)
`Тип closure записан так () -> Void
где () - список параметров, пустой
-> - стрелочка
Void - тип возвращаемого значения.

У типа функции обязательно указывать стрелочку и тип возвращаемого значения.
Без стрелочки и типа возвращаемого значения, компилятор будет думать, что это другой тип.

Например, в случае с `func completeClosures(a:(), b:())` пустой кортеж.

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +    b
Функции вызываются так 
```
a()
b()
```

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +    b
И задание звучит так:

> //7 Напишите функцию, которая принимает в себя две функции и возвращает функцию, которая при вызове выполнит первые две функции.

Вот сигнатура:
`func completeClosures(a: () -> Void, b: () -> Void) -> (() -> Void)`

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +func completeClosures(a:(), b:()){
Обратите внимание, что у типа функции первый элемент в круглых скобках - не кортеж, а список параметров.
Ну строго говоря конечно, это список параметров, представленный в виде кортежа)

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
>  }
Параметр by - кортеж, не функция.
Должен быть функцией.

Вот как это должно использоваться:
```
func superSort(arr: [Int], by: (Int, Int) -> Bool) -> [Int]{
    // ваша реализация
}

func forward(_ x1: Int, _ x2: Int)->Bool{
    return x2 > x1
}
let sortedArray = superSort(arr: intArray, by: forward)
print(sortedArray)
```

2021-01-12 13:06 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +}
Предложите еще один вариант.

2021-01-21 14:03 UTC, ios-review approved these changes
Можно мержить 👍

2021-01-21 14:03 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +let anotherStringNames = names.reduce("") {"\($0) \($1)"}.trimmingCharacters(in: .whitespaces) //второй вариант
еще один
`print(names.dropFirst().reduce(names.first ?? "") {"\($0) \($1)"})`

2021-01-21 14:03 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +var secondClosure: () -> Void = { print("2nd closure") }
эти две строки не нужны, так как не используются нигде

2021-01-21 14:03 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +completeClosures(a: {print("1")}, b: {print("2")})
чтобы проверить, что все ок нужно вызвать функцию, которую возвращает функция completeClosures:
`completeClosures(a: {print("1")}, b: {print("2")})()`

2021-01-21 14:03 UTC, ios-review commented on FunctionalProgramming.playground/Contents.swift
> +}
другая запись:
```
func completeClosures(a: @escaping() -> Void, b: @escaping() -> Void) -> (() -> Void){
    return {
        a()
        b()
    }
}
```

2021-02-02 15:42 UTC, merged